# Alte Domains -> kanonische Domain (Apex)
[[redirects]]
  from = "/*"
  to = "https://karinguetiger.ch/:splat"
  status = 301
  force = true
  conditions = { Host = ["awakensoul.ch", "www.awakensoul.ch", "thetasoul.ch", "www.thetasoul.ch"] }

[[redirects]]
  from = "https://www.karinguetiger.ch/*"
  to   = "https://karinguetiger.ch/:splat"
  status = 301
  force = true

# HTTP -> HTTPS Absicherung
[[redirects]]
  from = "http://karinguetiger.ch/*"
  to   = "https://karinguetiger.ch/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.karinguetiger.ch/*"
  to   = "https://karinguetiger.ch/:splat"
  status = 301
  force = true
