[[redirects]]
  from = "https://www.thetasoul.ch/"
  to = "https://karinguetiger.ch/"
  status = 301
  force = true
[[redirects]]
  from = "https://thetasoul.ch/"
  to = "https://karinguetiger.ch/"
  status = 301
  force = true
[[redirects]]
  from = "https://awakensoul.ch/"
  to = "https://karinguetiger.ch/"
  status = 301
  force = true
[[redirects]]
  from = "https://www.awakensoul.ch/"
  to = "https://karinguetiger.ch/"
  status = 301
  force = true
